<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\CatPais;

class CatPaisSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        
        $datos = [
            [ 'pais' => 'Afghanistan', 'iso_3' => 'AFG',  'phone_code' => '93',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Aland Islands', 'iso_3' => 'ALA',  'phone_code' => '358',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Albania', 'iso_3' => 'ALB',  'phone_code' => '355',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Algeria', 'iso_3' => 'DZA',  'phone_code' => '213',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'American Samoa', 'iso_3' => 'ASM',  'phone_code' => '1',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Andorra', 'iso_3' => 'AND',  'phone_code' => '376',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Angola', 'iso_3' => 'AGO',  'phone_code' => '244',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Anguilla', 'iso_3' => 'AIA',  'phone_code' => '1',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Antarctica', 'iso_3' => 'ATA',  'phone_code' => '672',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Antigua and Barbuda', 'iso_3' => 'ATG',  'phone_code' => '1',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Argentina', 'iso_3' => 'ARG',  'phone_code' => '54',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Armenia', 'iso_3' => 'ARM',  'phone_code' => '374',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Aruba', 'iso_3' => 'ABW',  'phone_code' => '297',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Australia', 'iso_3' => 'AUS',  'phone_code' => '61',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Austria', 'iso_3' => 'AUT',  'phone_code' => '43',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Azerbaijan', 'iso_3' => 'AZE',  'phone_code' => '994',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'The Bahamas', 'iso_3' => 'BHS',  'phone_code' => '1',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Bahrain', 'iso_3' => 'BHR',  'phone_code' => '973',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Bangladesh', 'iso_3' => 'BGD',  'phone_code' => '880',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Barbados', 'iso_3' => 'BRB',  'phone_code' => '1',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Belarus', 'iso_3' => 'BLR',  'phone_code' => '375',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Belgium', 'iso_3' => 'BEL',  'phone_code' => '32',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Belize', 'iso_3' => 'BLZ',  'phone_code' => '501',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Benin', 'iso_3' => 'BEN',  'phone_code' => '229',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Bermuda', 'iso_3' => 'BMU',  'phone_code' => '1',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Bhutan', 'iso_3' => 'BTN',  'phone_code' => '975',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Bolivia', 'iso_3' => 'BOL',  'phone_code' => '591',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Bosnia and Herzegovina', 'iso_3' => 'BIH',  'phone_code' => '387',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Botswana', 'iso_3' => 'BWA',  'phone_code' => '267',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Bouvet Island', 'iso_3' => 'BVT',  'phone_code' => '55',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Brazil', 'iso_3' => 'BRA',  'phone_code' => '55',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'British Indian Ocean Territory', 'iso_3' => 'IOT',  'phone_code' => '246',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Brunei', 'iso_3' => 'BRN',  'phone_code' => '673',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Bulgaria', 'iso_3' => 'BGR',  'phone_code' => '359',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Burkina Faso', 'iso_3' => 'BFA',  'phone_code' => '226',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Burundi', 'iso_3' => 'BDI',  'phone_code' => '257',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Cambodia', 'iso_3' => 'KHM',  'phone_code' => '855',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Cameroon', 'iso_3' => 'CMR',  'phone_code' => '237',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Canada', 'iso_3' => 'CAN',  'phone_code' => '1',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Cape Verde', 'iso_3' => 'CPV',  'phone_code' => '238',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Cayman Islands', 'iso_3' => 'CYM',  'phone_code' => '1',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Central African Republic', 'iso_3' => 'CAF',  'phone_code' => '236',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Chad', 'iso_3' => 'TCD',  'phone_code' => '235',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Chile', 'iso_3' => 'CHL',  'phone_code' => '56',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'China', 'iso_3' => 'CHN',  'phone_code' => '86',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Christmas Island', 'iso_3' => 'CXR',  'phone_code' => '61',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Cocos (Keeling) Islands', 'iso_3' => 'CCK',  'phone_code' => '61',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Colombia', 'iso_3' => 'COL',  'phone_code' => '57',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Comoros', 'iso_3' => 'COM',  'phone_code' => '269',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Congo', 'iso_3' => 'COG',  'phone_code' => '242',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Democratic Republic of the Congo', 'iso_3' => 'COD',  'phone_code' => '243',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Cook Islands', 'iso_3' => 'COK',  'phone_code' => '682',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Costa Rica', 'iso_3' => 'CRI',  'phone_code' => '506',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Ivory Coast', 'iso_3' => 'CIV',  'phone_code' => '225',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Croatia', 'iso_3' => 'HRV',  'phone_code' => '385',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Cuba', 'iso_3' => 'CUB',  'phone_code' => '53',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Cyprus', 'iso_3' => 'CYP',  'phone_code' => '357',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Czech Republic', 'iso_3' => 'CZE',  'phone_code' => '420',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Denmark', 'iso_3' => 'DNK',  'phone_code' => '45',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Djibouti', 'iso_3' => 'DJI',  'phone_code' => '253',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Dominica', 'iso_3' => 'DMA',  'phone_code' => '1',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Dominican Republic', 'iso_3' => 'DOM',  'phone_code' => '1',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Timor-Leste', 'iso_3' => 'TLS',  'phone_code' => '670',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Ecuador', 'iso_3' => 'ECU',  'phone_code' => '593',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Egypt', 'iso_3' => 'EGY',  'phone_code' => '20',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'El Salvador', 'iso_3' => 'SLV',  'phone_code' => '503',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Equatorial Guinea', 'iso_3' => 'GNQ',  'phone_code' => '240',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Eritrea', 'iso_3' => 'ERI',  'phone_code' => '291',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Estonia', 'iso_3' => 'EST',  'phone_code' => '372',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Ethiopia', 'iso_3' => 'ETH',  'phone_code' => '251',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Falkland Islands', 'iso_3' => 'FLK',  'phone_code' => '500',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Faroe Islands', 'iso_3' => 'FRO',  'phone_code' => '298',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Fiji Islands', 'iso_3' => 'FJI',  'phone_code' => '679',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Finland', 'iso_3' => 'FIN',  'phone_code' => '358',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'France', 'iso_3' => 'FRA',  'phone_code' => '33',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'French Guiana', 'iso_3' => 'GUF',  'phone_code' => '594',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'French Polynesia', 'iso_3' => 'PYF',  'phone_code' => '689',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'French Southern Territories', 'iso_3' => 'ATF',  'phone_code' => '262',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Gabon', 'iso_3' => 'GAB',  'phone_code' => '241',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'The Gambia', 'iso_3' => 'GMB',  'phone_code' => '220',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Georgia', 'iso_3' => 'GEO',  'phone_code' => '995',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Germany', 'iso_3' => 'DEU',  'phone_code' => '49',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Ghana', 'iso_3' => 'GHA',  'phone_code' => '233',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Gibraltar', 'iso_3' => 'GIB',  'phone_code' => '350',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Greece', 'iso_3' => 'GRC',  'phone_code' => '30',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Greenland', 'iso_3' => 'GRL',  'phone_code' => '299',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Grenada', 'iso_3' => 'GRD',  'phone_code' => '1',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Guadeloupe', 'iso_3' => 'GLP',  'phone_code' => '590',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Guam', 'iso_3' => 'GUM',  'phone_code' => '1',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Guatemala', 'iso_3' => 'GTM',  'phone_code' => '502',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Guernsey', 'iso_3' => 'GGY',  'phone_code' => '44',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Guinea', 'iso_3' => 'GIN',  'phone_code' => '224',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Guinea-Bissau', 'iso_3' => 'GNB',  'phone_code' => '245',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Guyana', 'iso_3' => 'GUY',  'phone_code' => '592',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Haiti', 'iso_3' => 'HTI',  'phone_code' => '509',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Heard Island and McDonald Islands', 'iso_3' => 'HMD',  'phone_code' => '672',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Honduras', 'iso_3' => 'HND',  'phone_code' => '504',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Hong Kong S.A.R.', 'iso_3' => 'HKG',  'phone_code' => '852',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Hungary', 'iso_3' => 'HUN',  'phone_code' => '36',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Iceland', 'iso_3' => 'ISL',  'phone_code' => '354',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'India', 'iso_3' => 'IND',  'phone_code' => '91',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Indonesia', 'iso_3' => 'IDN',  'phone_code' => '62',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Iran', 'iso_3' => 'IRN',  'phone_code' => '98',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Iraq', 'iso_3' => 'IRQ',  'phone_code' => '964',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Ireland', 'iso_3' => 'IRL',  'phone_code' => '353',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Israel', 'iso_3' => 'ISR',  'phone_code' => '972',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Italy', 'iso_3' => 'ITA',  'phone_code' => '39',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Jamaica', 'iso_3' => 'JAM',  'phone_code' => '1',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Japan', 'iso_3' => 'JPN',  'phone_code' => '81',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Jersey', 'iso_3' => 'JEY',  'phone_code' => '44',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Jordan', 'iso_3' => 'JOR',  'phone_code' => '962',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Kazakhstan', 'iso_3' => 'KAZ',  'phone_code' => '7',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Kenya', 'iso_3' => 'KEN',  'phone_code' => '254',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Kiribati', 'iso_3' => 'KIR',  'phone_code' => '686',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'North Korea', 'iso_3' => 'PRK',  'phone_code' => '850',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'South Korea', 'iso_3' => 'KOR',  'phone_code' => '82',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Kuwait', 'iso_3' => 'KWT',  'phone_code' => '965',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Kyrgyzstan', 'iso_3' => 'KGZ',  'phone_code' => '996',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Laos', 'iso_3' => 'LAO',  'phone_code' => '856',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Latvia', 'iso_3' => 'LVA',  'phone_code' => '371',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Lebanon', 'iso_3' => 'LBN',  'phone_code' => '961',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Lesotho', 'iso_3' => 'LSO',  'phone_code' => '266',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Liberia', 'iso_3' => 'LBR',  'phone_code' => '231',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Libya', 'iso_3' => 'LBY',  'phone_code' => '218',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Liechtenstein', 'iso_3' => 'LIE',  'phone_code' => '423',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Lithuania', 'iso_3' => 'LTU',  'phone_code' => '370',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Luxembourg', 'iso_3' => 'LUX',  'phone_code' => '352',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Macau S.A.R.', 'iso_3' => 'MAC',  'phone_code' => '853',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'North Macedonia', 'iso_3' => 'MKD',  'phone_code' => '389',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Madagascar', 'iso_3' => 'MDG',  'phone_code' => '261',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Malawi', 'iso_3' => 'MWI',  'phone_code' => '265',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Malaysia', 'iso_3' => 'MYS',  'phone_code' => '60',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Maldives', 'iso_3' => 'MDV',  'phone_code' => '960',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Mali', 'iso_3' => 'MLI',  'phone_code' => '223',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Malta', 'iso_3' => 'MLT',  'phone_code' => '356',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Man (Isle of)', 'iso_3' => 'IMN',  'phone_code' => '44',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Marshall Islands', 'iso_3' => 'MHL',  'phone_code' => '692',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Martinique', 'iso_3' => 'MTQ',  'phone_code' => '596',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Mauritania', 'iso_3' => 'MRT',  'phone_code' => '222',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Mauritius', 'iso_3' => 'MUS',  'phone_code' => '230',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Mayotte', 'iso_3' => 'MYT',  'phone_code' => '262',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Mexico', 'iso_3' => 'MEX',  'phone_code' => '52',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Micronesia', 'iso_3' => 'FSM',  'phone_code' => '691',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Moldova', 'iso_3' => 'MDA',  'phone_code' => '373',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Monaco', 'iso_3' => 'MCO',  'phone_code' => '377',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Mongolia', 'iso_3' => 'MNG',  'phone_code' => '976',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Montenegro', 'iso_3' => 'MNE',  'phone_code' => '382',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Montserrat', 'iso_3' => 'MSR',  'phone_code' => '1',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Morocco', 'iso_3' => 'MAR',  'phone_code' => '212',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Mozambique', 'iso_3' => 'MOZ',  'phone_code' => '258',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Myanmar', 'iso_3' => 'MMR',  'phone_code' => '95',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Namibia', 'iso_3' => 'NAM',  'phone_code' => '264',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Nauru', 'iso_3' => 'NRU',  'phone_code' => '674',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Nepal', 'iso_3' => 'NPL',  'phone_code' => '977',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Bonaire, Sint Eustatius and Saba', 'iso_3' => 'BES',  'phone_code' => '599',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Netherlands', 'iso_3' => 'NLD',  'phone_code' => '31',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'New Caledonia', 'iso_3' => 'NCL',  'phone_code' => '687',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'New Zealand', 'iso_3' => 'NZL',  'phone_code' => '64',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Nicaragua', 'iso_3' => 'NIC',  'phone_code' => '505',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Niger', 'iso_3' => 'NER',  'phone_code' => '227',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Nigeria', 'iso_3' => 'NGA',  'phone_code' => '234',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Niue', 'iso_3' => 'NIU',  'phone_code' => '683',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Norfolk Island', 'iso_3' => 'NFK',  'phone_code' => '672',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Northern Mariana Islands', 'iso_3' => 'MNP',  'phone_code' => '1',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Norway', 'iso_3' => 'NOR',  'phone_code' => '47',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Oman', 'iso_3' => 'OMN',  'phone_code' => '968',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Pakistan', 'iso_3' => 'PAK',  'phone_code' => '92',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Palau', 'iso_3' => 'PLW',  'phone_code' => '680',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Palestinian Territory Occupied', 'iso_3' => 'PSE',  'phone_code' => '970',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Panama', 'iso_3' => 'PAN',  'phone_code' => '507',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Papua New Guinea', 'iso_3' => 'PNG',  'phone_code' => '675',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Paraguay', 'iso_3' => 'PRY',  'phone_code' => '595',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Peru', 'iso_3' => 'PER',  'phone_code' => '51',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Philippines', 'iso_3' => 'PHL',  'phone_code' => '63',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Pitcairn Island', 'iso_3' => 'PCN',  'phone_code' => '870',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Poland', 'iso_3' => 'POL',  'phone_code' => '48',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Portugal', 'iso_3' => 'PRT',  'phone_code' => '351',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Puerto Rico', 'iso_3' => 'PRI',  'phone_code' => '1',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Qatar', 'iso_3' => 'QAT',  'phone_code' => '974',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Reunion', 'iso_3' => 'REU',  'phone_code' => '262',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Romania', 'iso_3' => 'ROU',  'phone_code' => '40',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Russia', 'iso_3' => 'RUS',  'phone_code' => '7',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Rwanda', 'iso_3' => 'RWA',  'phone_code' => '250',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Saint Helena', 'iso_3' => 'SHN',  'phone_code' => '290',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Saint Kitts and Nevis', 'iso_3' => 'KNA',  'phone_code' => '1',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Saint Lucia', 'iso_3' => 'LCA',  'phone_code' => '1',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Saint Pierre and Miquelon', 'iso_3' => 'SPM',  'phone_code' => '508',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Saint Vincent and the Grenadines', 'iso_3' => 'VCT',  'phone_code' => '1',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Saint-Barthelemy', 'iso_3' => 'BLM',  'phone_code' => '590',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Saint-Martin (French part)', 'iso_3' => 'MAF',  'phone_code' => '590',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Samoa', 'iso_3' => 'WSM',  'phone_code' => '685',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'San Marino', 'iso_3' => 'SMR',  'phone_code' => '378',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Sao Tome and Principe', 'iso_3' => 'STP',  'phone_code' => '239',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Saudi Arabia', 'iso_3' => 'SAU',  'phone_code' => '966',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Senegal', 'iso_3' => 'SEN',  'phone_code' => '221',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Serbia', 'iso_3' => 'SRB',  'phone_code' => '381',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Seychelles', 'iso_3' => 'SYC',  'phone_code' => '248',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Sierra Leone', 'iso_3' => 'SLE',  'phone_code' => '232',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Singapore', 'iso_3' => 'SGP',  'phone_code' => '65',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Slovakia', 'iso_3' => 'SVK',  'phone_code' => '421',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Slovenia', 'iso_3' => 'SVN',  'phone_code' => '386',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Solomon Islands', 'iso_3' => 'SLB',  'phone_code' => '677',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Somalia', 'iso_3' => 'SOM',  'phone_code' => '252',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'South Africa', 'iso_3' => 'ZAF',  'phone_code' => '27',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'South Georgia', 'iso_3' => 'SGS',  'phone_code' => '500',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'South Sudan', 'iso_3' => 'SSD',  'phone_code' => '211',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Spain', 'iso_3' => 'ESP',  'phone_code' => '34',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Sri Lanka', 'iso_3' => 'LKA',  'phone_code' => '94',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Sudan', 'iso_3' => 'SDN',  'phone_code' => '249',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Suriname', 'iso_3' => 'SUR',  'phone_code' => '597',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Svalbard and Jan Mayen Islands', 'iso_3' => 'SJM',  'phone_code' => '47',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Eswatini', 'iso_3' => 'SWZ',  'phone_code' => '268',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Sweden', 'iso_3' => 'SWE',  'phone_code' => '46',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Switzerland', 'iso_3' => 'CHE',  'phone_code' => '41',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Syria', 'iso_3' => 'SYR',  'phone_code' => '963',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Taiwan', 'iso_3' => 'TWN',  'phone_code' => '886',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Tajikistan', 'iso_3' => 'TJK',  'phone_code' => '992',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Tanzania', 'iso_3' => 'TZA',  'phone_code' => '255',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Thailand', 'iso_3' => 'THA',  'phone_code' => '66',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Togo', 'iso_3' => 'TGO',  'phone_code' => '228',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Tokelau', 'iso_3' => 'TKL',  'phone_code' => '690',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Tonga', 'iso_3' => 'TON',  'phone_code' => '676',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Trinidad and Tobago', 'iso_3' => 'TTO',  'phone_code' => '1',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Tunisia', 'iso_3' => 'TUN',  'phone_code' => '216',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Turkey', 'iso_3' => 'TUR',  'phone_code' => '90',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Turkmenistan', 'iso_3' => 'TKM',  'phone_code' => '993',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Turks and Caicos Islands', 'iso_3' => 'TCA',  'phone_code' => '1',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Tuvalu', 'iso_3' => 'TUV',  'phone_code' => '688',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Uganda', 'iso_3' => 'UGA',  'phone_code' => '256',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Ukraine', 'iso_3' => 'UKR',  'phone_code' => '380',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'United Arab Emirates', 'iso_3' => 'ARE',  'phone_code' => '971',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'United Kingdom', 'iso_3' => 'GBR',  'phone_code' => '44',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'United States', 'iso_3' => 'USA',  'phone_code' => '1',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'United States Minor Outlying Islands', 'iso_3' => 'UMI',  'phone_code' => '1',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Uruguay', 'iso_3' => 'URY',  'phone_code' => '598',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Uzbekistan', 'iso_3' => 'UZB',  'phone_code' => '998',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Vanuatu', 'iso_3' => 'VUT',  'phone_code' => '678',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Vatican City State (Holy See)', 'iso_3' => 'VAT',  'phone_code' => '379',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Venezuela', 'iso_3' => 'VEN',  'phone_code' => '58',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Vietnam', 'iso_3' => 'VNM',  'phone_code' => '84',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Virgin Islands (British)', 'iso_3' => 'VGB',  'phone_code' => '1',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Virgin Islands (US)', 'iso_3' => 'VIR',  'phone_code' => '1',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Wallis and Futuna Islands', 'iso_3' => 'WLF',  'phone_code' => '681',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Western Sahara', 'iso_3' => 'ESH',  'phone_code' => '212',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Yemen', 'iso_3' => 'YEM',  'phone_code' => '967',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Zambia', 'iso_3' => 'ZMB',  'phone_code' => '260',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Zimbabwe', 'iso_3' => 'ZWE',  'phone_code' => '263',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Kosovo', 'iso_3' => 'XKX',  'phone_code' => '383',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Curaçao', 'iso_3' => 'CUW',  'phone_code' => '599',  'usuario_ins' => 1,  'created_at' => '2026-08-14'], 
            [ 'pais' => 'Sint Maarten (Dutch part)', 'iso_3' => 'SXM',  'phone_code' => '1721',  'usuario_ins' => 1,  'created_at' => '2026-08-14']
        ];

        CatPais::insert($datos);
    }
}
